### ISSUE TITLE
About reproducing the results in Synthia to Cityscape dataset

### ISSUE THREAD

**Issue by kagawa588** [BIT-DA/SePiCo#10]
Hi,

Thanks for your impressive work. I am interested in reproducing the results you reported in paper. I tried Synthia to Cityscape dataset and adopts DistCL based on DAFormer, but my final results is 3 mIoU lower than your results, which is 64.3mIoU. I would like to ask if the parameters you used are the same as DAFormer? Or could you please upload a copy of your parameters used? 

Thanks

**Comment by BinhuiXie** [comment]
Hi @kagawa588,

Thank you for your question. It is weird and impossible. 

You can check our released checkpoint and the config is also available at https://drive.google.com/drive/folders/1BW4W5ehcuu8OWq8XlDFiZuyQImr_ibOe?usp=sharing.
