### ISSUE TITLE
训练的时候使用mmsegmentation的tools/train.py可以吗？

### ISSUE THREAD

**Issue by wzr0108** [BIT-DA/SePiCo#12]

**Comment by BinhuiXie** [comment]
您好@wzr0108，感谢对我们工作的关注～

训练时候的主程序`run_experiments.py`中调用的就是`mmsegmentation的tools/train.py`

https://github.com/BIT-DA/SePiCo/blob/08b47ed8a7e74c6ce9b063117d1d4837949686d9/run_experiments.py#L17

**Comment by wzr0108** [comment]
非常感谢

**Comment by BinhuiXie** [comment]
Thanks for your interest in SePiCo. I'm closing this issue. Feel free to ask if you have further questions.
