### ISSUE TITLE
AssertionError: Parameter `mean` required

### ISSUE THREAD

**Issue by logicxwang** [BIT-DA/SePiCo#13]
contrastive_loss.py line:114，The mean parameter was not passed in。what is the mean parameter?

**Comment by BinhuiXie** [comment]
Hi @1994crazyboy. Thanks for your interest. `mean` denotes global category prototypes, i.e., the mean statistics of features in each category.

**Comment by BinhuiXie** [comment]
I believe the issue at hand has been resolved, so I am closing this issue. If you have further questions, please feel free to ask.

**Comment by logicxwang** [comment]
It has been solved. Thank you very much
