### ISSUE TITLE
About Cityscapes-->DarkZurich

### ISSUE THREAD

**Issue by XiaRho** [BIT-DA/SePiCo#14]
Hi,
Thank you for your wonderful work! I am more interested in the Cityscapes-->DarkZurich adaptation. However, in your run_experiments.py, there is no corresponding code implementation. Therefore, I build my own implementation of the Cityscapes-->DarkZurich code, but the results are poor, with only 28.69 MIoU on the validation set. Here is my training file, can you point out my mistakes. Thank you very much！
[20230203_115623.log](https://github.com/BIT-DA/SePiCo/files/10607850/20230203_115623.log)

**Comment by BinhuiXie** [comment]
Hi @XiaRho, thanks for your interest in SePiCo. The code for Cityscapes to Dark Zurich is available now. Pls, check it. 

 Also, look into the evaluation at https://github.com/BIT-DA/SePiCo#evaluation-on-dark-zurich.

**Comment by XiaRho** [comment]
Hi @BinhuiXie, thank you so much for your help! Your response is really useful for me. l will check your updated code.
