### ISSUE TITLE
如果打算像你们那样，给自定义的损失函数传入mask和feat，该如何在mmseg框架下更改？

### ISSUE THREAD

**Issue by QChhh123** [BIT-DA/SePiCo#17]

**Comment by BinhuiXie** [comment]
Hi @QChhh123 

Thank you for being so interested. 

First, you can follow the tutorial on MMSegmentation to define a new loss function. https://mmsegmentation.readthedocs.io/zh_CN/latest/advanced_guides/add_models.html#loss

In our repo, you can refer to this file [`contrastive_loss.py`](https://github.com/BIT-DA/SePiCo/blob/0774b56e2c566e315a25997b915dd68076606149/mmseg/models/losses/contrastive_loss.py). 
And if you expect feat and mask in the loss function, the following lines might be helpful.
https://github.com/BIT-DA/SePiCo/blob/0774b56e2c566e315a25997b915dd68076606149/mmseg/models/losses/contrastive_loss.py#L349-L355

**Comment by QChhh123** [comment]
Thank you for your reply. I may not have described my problem clearly. If I expect feat and mask, how to modify the config file？ And, in which part, the feat and mask are passed into the contrastive_loss.



---原始邮件---
发件人: "Binhui Xie ***@***.***&gt;
发送时间: 2023年4月8日(周六) 中午11:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BIT-DA/SePiCo] 如果打算像你们那样，给自定义的损失函数传入mask和feat，该如何在mmseg框架下更改？ (Issue #17)




 
Hi @QChhh123
 
Thank you for being so interested.
 
First, you can follow the tutorial on MMSegmentation to define a new loss function. https://mmsegmentation.readthedocs.io/zh_CN/latest/advanced_guides/add_models.html#loss
 
In our repo, you can refer to this file contrastive_loss.py.
 And if you expect feat and mask in the loss function, the following lines might be helpful.
 https://github.com/BIT-DA/SePiCo/blob/0774b56e2c566e315a25997b915dd68076606149/mmseg/models/losses/contrastive_loss.py#L349-L355

**Comment by BinhuiXie** [comment]
1. config file

https://github.com/BIT-DA/SePiCo/blob/0774b56e2c566e315a25997b915dd68076606149/configs/_base_/models/daformer_sepaspp_proj_mitb5.py#L11

we define a new SEGMENTORS `EncoderDecoderProjector` to include the auxiliary head for contrastive loss.

https://github.com/BIT-DA/SePiCo/blob/0774b56e2c566e315a25997b915dd68076606149/configs/_base_/models/daformer_sepaspp_proj_mitb5.py#L36-L50


2. the path, take the target contrastive loss as an example.

https://github.com/BIT-DA/SePiCo/blob/0774b56e2c566e315a25997b915dd68076606149/mmseg/models/uda/sepico.py#L337-L338

https://github.com/BIT-DA/SePiCo/blob/0774b56e2c566e315a25997b915dd68076606149/mmseg/models/segmentors/encoder_decoder_projector.py#L195-L196

https://github.com/BIT-DA/SePiCo/blob/0774b56e2c566e315a25997b915dd68076606149/mmseg/models/segmentors/encoder_decoder_projector.py#L134-L135

https://github.com/BIT-DA/SePiCo/blob/0774b56e2c566e315a25997b915dd68076606149/mmseg/models/decode_heads/decode_head_decorator.py#L194

https://github.com/BIT-DA/SePiCo/blob/0774b56e2c566e315a25997b915dd68076606149/mmseg/models/losses/contrastive_loss.py#L349-L355

Hope it helps.

**Comment by QChhh123** [comment]
Thank you very much for your answer. I have benefited a lot from it

**Comment by BinhuiXie** [comment]
I believe the issue at hand was addressed, as such I'm closing this. Feel free to ask if you have further questions.
