### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by TianX1nYu** [BIT-DA/SePiCo#19]
Since we don't have a V100, how many hours did SePiCo use deelabv2 to train GTA5→Cityscapes on the V100 to reach the best score of 61mIoU?

**Comment by BinhuiXie** [comment]
Hi @TianX1nYu,

Thank you for your attention! Our SePiCo (DeepLab-2) was trained on a single V100 in less than one day.

**Comment by BinhuiXie** [comment]
I'm closing this issue. Pls feel free to ping me if there are any question.
