### ISSUE TITLE
About Synthia-Cityscapes dataset

### ISSUE THREAD

**Issue by kagawa588** [BIT-DA/SePiCo#7]
Hi,

Thanks for your great work! I would like to know if you could provide a checkpoint file of the synthia-cityscape dataset, since I can not reproduce the results in TABLE 4 (64.3) in the paper myself.

Thanks!

**Comment by BinhuiXie** [comment]
Hi @muchen006 

:partying_face: All checkpoints are available now.

**Comment by kagawa588** [comment]
Hi Binhui,

Thanks so much! 

Have a great day!

**Comment by muchen006** [comment]
Finished
