### ISSUE TITLE
Something about mIoU performance

### ISSUE THREAD

**Issue by wanderHZ** [BIT-DA/SePiCo#8]
Hi，could you tell me whether the final performance of the model or the highest performance in training is reported in the paper？Such as 61.0(gtav to cityscapes).

**Comment by BinhuiXie** [comment]
Hi @wanderHZ 

We just keep the last checkpoint (last.pth) for evaluation.

**Comment by wanderHZ** [comment]
I see. Thank you for your prompt reply！

**Comment by BinhuiXie** [comment]
Thanks for your interest~

I'm closing this issue. Pls feel free to ping me if there are further questions.
