### ISSUE TITLE
Replicating the results

### ISSUE THREAD

**Issue by NazaninMn** [BIT-DA/SePiCo#9]
Hi, I would like to replicate the results represented in this paper for GTAV → Cityscapes (DAFormer based) experiment. I set the Experiment ID to 4, but I still could not get the same or close results. The results that I am getting is around 64 percent while it has been reported 70 percent in the paper. Could you please let me know if I should do any thing other than ID setting to replicate the results?

**Comment by BinhuiXie** [comment]
Hi @NazaninMn 

Thanks for your attention. Could you please provide the training log and I will check it.

**Comment by BinhuiXie** [comment]
I'm closing this issue. Pls feel free to ping me if there are further questions.
